var JSLang = {
    "zh": {
        "beepAudio": "提示音类型",
        "tensorAI": "- 人工智能 -",
        "imageNet": "ImageNet 图像分类",
        "cocoSSD": "CocoSSD 对象检测",
        "deepLab": "DeepLab 图像分割",
        "blazeFace": "人脸识别",
        "mediaPipe": "手势检测",
        "ocr": "蜂鸣器",
        "qr": "二维码识别",
        "coco": "物品识别",
        "MoveNet": "MoveNet 关节点识别",
        "Bert": "文本问答",
        "SpeechCMD": "SpeechCMD 语音指令",
        "syncInterval": "自动更新频率",
        "sendInterval": "自动发送频率",
        "never": "从不",
        "i1min": "每分钟一次",
        "i3min": "每3分钟一次",
        "i5min": "每5分钟一次",
        "i10min": "每10分钟一次",
        "i15min": "每15分钟一次",
        "i30min": "每30分钟一次",
        "i60min": "每60分钟一次",
        "dstTopicLenIllegal": "动作主题不能为空",
        "dstMessageLenIllegal": "动作消息不能为空",
        "conditionLenIllegal": "条件值不能为空",
        "srcTopic": "条件主题",
        "condition": "触发条件",
        "conditionRelation": "条件关系",
        "dstTopic": "动作主题",
        "dstMessage": "动作消息",
        "invalidContent": "数据内容无效",
        "backRun": "后台运行数据视图和逻辑视图",
        "stopBackRun": "停止后台运行",
        "backRunErr": "后台运行过程中发生错误",
        "editProper": "修改项目属性",
        "viewProject": "查看和编辑项目内容",
        "illegalCycle": "逻辑视图中存在循环方法，不允许后台运行",
        "codeException": "当前项目的逻辑视图存在无法在后台运行的内容",
        "loading": "加载中",
        "loading2": "更改中",
        "wrongAcc": "用户名或密码错误",
        "noKey": "请输入Mixly Key",
        "noVfCode": "请输入项目授权码",
        "modify": "更改项目",
        "rename": "更改名称",
        "copy": "复制项目",
        "share": "共享项目",
        "delete": "删除项目",
        "renamePrj": "更改项目名称",
        "newPrjName": "请输入新项目名称",
        "lengthRes": "项目名称长度应为3-10个字符",
        "prjExist": "项目名称已存在",
        "copyName": "项目副本名称",
        "prjOverflow": "您管理的项目数量已达到上限",
        "shareConfirm": "确认为您当前的项目布局生成一个授权码？他人获得该授权码后，将可以访问或复制您的当前项目。",
        "shareSuccess": "共享成功",
        "aucode": "项目授权码",
        "guestURL": "访客访问链接",
        "logicError": "逻辑视图发生错误，请前往修改。",
        "prjManage": "项目管理",
        "blocklyDev": "图形化编程模式正在开发中，敬请期待！",
        "hardwarePass": "连接配置",
        "connected": "已连接至通讯服务器",
        "connectCount": "个设备已连接",
        "connecting": "正在连接通讯服务器",
        "disconnected": "连接已断开",
        "pauseBeforeModify": "若要修改逻辑代码，请先暂停项目。",
        "console": "输出",
        "downloading": "正在下载项目数据",
        "prj404": "项目不存在！",
        "slow": "检测到渲染卡顿",
        "remindClear": "，可能是由于数据视图中的数据过多，请您及时清除无用数据。",
        "duringOff": "离线期间，项目共收到",
        "messageRem": "条消息。<br>这些消息将被存储在“数据”视图中。",
        "topic": "主题",
        "message": "消息",
        "time": "时间",
        "listener": "监听主题：",
        "select": "请选择",
        "monitor": "数据监视表",
        "download": "下载",
        "clear": "清空当前",
        "rtchart": "可视化窗格",
        "clearAll": "删除主题",
        "sender": "发送主题：",
        "value": "值",
        "noData": "暂无数据",
        "sendString": "发送文本数据",
        "topicUnset": "请设置发送主题。",
        "sendJSON": "发送JSON数据",
        "key": "键",
        "JSONempty": "JSON消息必须至少包含一个键值",
        "addKey": "添加一个键值",
        "invalidJSON": "发送内容无效",
        "control": "- 控制 -",
        "switch": "开关",
        "button": "按键",
        "slider": "滑杆",
        "joystick": "摇杆手柄",
        "RGB": "RGB色盘",
        "bulb": "指示灯",
        "timer": "定时触发器",
        "trigger": "条件触发器",
        "magic": "装饰框",
        "pixel": "点阵屏",
        "video": "视频",
        "widget": "组件",
        "data": "- 数据 -",
        "lineChart": "折线图表",
        "barChart": "投票器",
        "dataTable": "数据表格",
        "dataMap": "数据地图",
        "dashboard": "仪表盘",
        "weather": "实时气象仪",
        "text": "- 媒体 -",
        "keyboard": "文本输入",
        "screen": "文本显示屏",
        "decorate": "- 装饰 -",
        "label": "标签",
        "picture": "图片 / 视频",
        "ble": "蓝牙转发器",
        "unitName": "组件名称",
        "messTopic": "消息主题",
        "options": "选项列表（逗号分隔）",
        "readMessTopic": "读取消息主题",
        "writeMessTopic": "写入消息主题",
        "triggerTopic": "触发消息主题",
        "triggerMessage": "触发消息内容",
        "triggerInterval": "触发间隔(毫秒)",
        "triggerTimes": "次数上限(0=无限)",
        "feedbackMode": "反馈模式",
        "sameUnit": "当前项目中已存在一个同名组件，请重新命名。",
        "nameLenIllegal": "组件名称非法（长度应为1-10个字符）",
        "topicLenIllegal": "消息主题非法（长度应为1-10个字符）",
        "messageLenIllegal": "消息内容不能为空",
        "illegalInterval": "最小触发间隔为500毫秒",
        "illegalTimes": "触发次数应为非负整数",
        "invalidSlideRange": "滑动数值设置有误",
        "invalidPixel": "像素设置有误（最大值为100）",
        "slideRange": "滑动范围",
        "hideTitle": "内部组件标题",
        "min": "最小值",
        "max": "最大值",
        "step": "步长",
        "xpixel": "水平像素",
        "ypixel": "垂直像素",
        "show": "显示",
        "hide": "隐藏",
        "choicesList": "选项列表",
        "recvMode": "接收模式",
        "single": "单选",
        "multiple": "多选",
        "listEmpty": "选项列表不能为空",
        "location": "采集位置",
        "province": "请选择省级区划",
        "city": "请选择市县",
        "district": "请选择区域",
        "locationSet": "请设置天气数据采集地域",
        "columns": "列名",
        "color": "颜色",
        "bleTarget": "蓝牙设备",
        "blue": "蓝色",
        "green": "绿色",
        "cyan": "青色",
        "red": "红色",
        "yellow": "黄色",
        "gray": "灰色",
        "columnsSet": "请设置列名",
        "displayRange": "指示范围",
        "mod5": "取值范围的极差必须为5的正整数倍。",
        "displayText": "显示文本",
        "imageURL": "图片链接",
        "saveSuccess": "项目保存成功",
        "saveFail": "项目保存失败 ",
        "info": "提示信息",
        "confirmDel": "确定删除项目",
        "confirm": "确定",
        "deleting": "删除中...",
        "error": "错误信息",
        "deleteFail": "删除失败",
        "cancel": "取消",
        "createPrj": "创建一个项目",
        "createPrjName": "请输入新项目名称",
        "import": "导入一个项目",
        "importData": "导入用户数据",
        "importDataWarning": "同名项目将被覆盖，请谨慎操作",
        "inputAuCode": "请输入项目授权码",
        "invalidAU": "项目授权码无效（或已失效）",
        "incorrectAU": "项目授权码格式不正确",
        "speedLimit": "发送数据频率过高，已进行限制。",
        "diffRepeat": "两次输入的密码不一致",
        "userEmpty": "用户名不能为空",
        "passEmpty": "密码不能为空",
        "userExist": "用户名已存在",
        "emailEmpty": "请输入电子邮件地址",
        "querying": "查询中...",
        "queryS": "查询成功",
        "queryF": "查询失败",
        "queryN": "用户不存在",
        "answerEmpty": "答案不能为空！",
        "resetSuccess": "密码重置成功",
        "wrongAns": "答案错误",
        "shareAt": "分享于",
        "invalidAUPrj": "授权项目不存在或已失效。",
        "clearData": "清除数据",
        "confirmClear": "确认清除",
        'prjs': "项目中的",
        'clearAsk': "条离线存储数据吗？",
        "clearS": "清除成功",
        "guide": "使用指南",
        "settingP": "设置中...",
        "settingS": "设置成功",
        "settingF": "设置失败",
        "option": "选项",
        "noData": "暂无数据",
        "updating": "更新中...",
        "updateF": "更新失败",
        "mapJSON": "一个地图组件收到了无效的JSON消息。",
        "invalidUType": "不正确的组件类别。",
        "noUnitFound": "未找到组件。",
        "platformList": "已登录平台",
        "deviceList": "已连接设备",
        "camera": "摄像头",
        "mic": "语音识别",
        "tinydb": "下拉选项",
        "resolution": "分辨率",
        "fps": "帧率",
        'tdb': "TinyDB"
    },
    "tw": {
        "beepAudio": "提示音類型",
        "tensorAI": "- 人工智慧 -",
        "imageNet": "ImageNet 圖像分類",
        "cocoSSD": "CocoSSD 物件偵測",
        "deepLab": "DeepLab 圖像分割",
        "blazeFace": "人臉辨識",
        "mediaPipe": "手勢偵測",
        "ocr": "蜂鳴器",
        "qr": "QR Code 辨識",
        "coco": "物件辨識",
        "MoveNet": "MoveNet 關節點辨識",
        "Bert": "文字問答",
        "SpeechCMD": "SpeechCMD 語音指令",
        "syncInterval": "自動更新頻率",
        "sendInterval": "自動發送頻率",
        "never": "從不",
        "i1min": "每分鐘一次",
        "i3min": "每3分鐘一次",
        "i5min": "每5分鐘一次",
        "i10min": "每10分鐘一次",
        "i15min": "每15分鐘一次",
        "i30min": "每30分鐘一次",
        "i60min": "每60分鐘一次",
        "dstTopicLenIllegal": "動作主題不能為空",
        "dstMessageLenIllegal": "動作消息不能為空",
        "conditionLenIllegal": "條件值不能為空",
        "srcTopic": "條件主題",
        "condition": "觸發條件",
        "conditionRelation": "條件關係",
        "dstTopic": "動作主題",
        "dstMessage": "動作消息",
        "invalidContent": "數據內容無效",
        "backRun": "後台運行數據視圖和邏輯視圖",
        "stopBackRun": "停止後台運行",
        "backRunErr": "後台運行過程中發生錯誤",
        "editProper": "修改項目屬性",
        "viewProject": "查看和編輯項目內容",
        "illegalCycle": "邏輯視圖中存在迴圈方法，不允許後台運行",
        "codeException": "代碼內部存在錯誤",
        "loading": "加載中",
        "loading2": "更改中",
        "wrongAcc": "用戶名或密碼錯誤",
        "noKey": "請輸入Mixly Key",
        "noVfCode": "請輸入專案授權碼",
        "modify": "更改項目",
        "rename": "更改名稱",
        "copy": "復製項目",
        "share": "共享項目",
        "delete": "刪除項目",
        "renamePrj": "更改項目名稱",
        "newPrjName": "請輸入新項目名稱",
        "lengthRes": "項目名稱長度應為3-10個字符",
        "prjExist": "項目名稱已存在",
        "copyName": "項目副本名稱",
        "prjOverflow": "您管理的項目數量已達到上限",
        "shareConfirm": "確認為您當前的項目布局生成一個授權碼？他人獲得該授權碼後，將可以訪問或復製您的當前項目。",
        "shareSuccess": "共享成功",
        "aucode": "項目授權碼",
        "guestURL": "訪客訪問鏈接",
        "logicError": "邏輯視圖發生錯誤，請前往修改。",
        "prjManage": "項目管理",
        "blocklyDev": "圖形化編程模式正在開發中，敬請期待！",
        "hardwarePass": "連接配置",
        "connected": "已連接至通訊服務器",
        "connectCount": "個設備已連接",
        "connecting": "正在連接通訊服務器",
        "disconnected": "連接已斷開",
        "pauseBeforeModify": "若要修改邏輯代碼，請先暫停項目。",
        "console": "輸出",
        "downloading": "正在下載項目數據",
        "prj404": "項目不存在！",
        "slow": "檢測到渲染卡頓",
        "remindClear": "，可能是由於數據視圖中的數據過多，請您及時清除無用數據。",
        "duringOff": "離線期間，項目共收到",
        "messageRem": "條消息。<br>這些消息將被存儲在「數據」視圖中。",
        "topic": "主題",
        "message": "消息",
        "triggerTopic": "觸發消息主題",
        "triggerMessage": "觸發消息內容",
        "triggerInterval": "觸發間隔(毫秒)",
        "triggerTimes": "次數上限（0 = 無限）",
        "time": "時間",
        "listener": "監聽主題：",
        "select": "請選擇",
        "monitor": "數據監視表",
        "download": "下載數據",
        "clear": "清空本主題數據",
        "clearAll": "移除主題",
        "rtchart": "可視化窗格",
        "sender": "發送主題：",
        "value": "值",
        "noData": "暫無數據",
        "sendString": "發送文本數據",
        "topicUnset": "請設置發送主題。",
        "sendJSON": "發送JSON數據",
        "key": "鍵",
        "JSONempty": "JSON消息必須至少包含一個鍵值",
        "addKey": "添加一個鍵值",
        "invalidJSON": "發送內容無效",
        "control": "- 控製 -",
        "switch": "開關",
        "button": "按鍵",
        "slider": "滑桿",
        "joystick": "搖桿手柄",
        "RGB": "RGB色盤",
        "bulb": "指示燈",
        "timer": "定時觸發器",
        "trigger": "條件觸發器",
        "magic": "框",
        "pixel": "點陣屏",
        "video": "視頻",
        "widget": "小部件",
        "data": "- 數據 -",
        "lineChart": "折線圖表",
        "barChart": "柱狀圖表",
        "dataTable": "數據表格",
        "dataMap": "數據地圖",
        "dashboard": "儀表盤",
        "weather": "實時氣象儀",
        "text": "- 媒體 -",
        "keyboard": "文本輸入",
        "screen": "文本顯示屏",
        "decorate": "- 裝飾 -",
        "label": "標簽",
        "picture": "圖片 / 視頻",
        "ble": "藍牙Hub",
        "unitName": "組件名稱",
        "messTopic": "消息主題",
        "options": "選項列表（逗號分隔）",
        "readMessTopic": "讀取消息主題",
        "writeMessTopic": "寫入消息主題",
        "feedbackMode": "反饋模式",
        "sameUnit": "當前項目中已存在一個同名組件，請重新命名。",
        "nameLenIllegal": "組件名稱非法（長度應為1-10個字符）",
        "topicLenIllegal": "消息主題非法（長度應為1-10個字符）",
        "illegalInterval": "最小觸髮間隔為500毫秒",
        "illegalTimes": "觸發次數應為非負整數",
        "messageLenIllegal": "消息內容不能為空",
        "invalidSlideRange": "滑動數值設置有誤",
        "invalidPixel": "像素值應為<101的非負整數",
        "slideRange": "滑動範圍",
        "hideTitle": "內部元件標題",
        "min": "最小值",
        "max": "最大值",
        "step": "步長",
        "xpixel": "水平像素",
        "ypixel": "垂直像素",
        "show": "顯示",
        "hide": "隱藏",
        "choicesList": "選項列表",
        "recvMode": "接收模式",
        "single": "單選",
        "multiple": "多選",
        "listEmpty": "選項列表不能為空",
        "location": "采集位置",
        "province": "請選擇省級區劃",
        "city": "請選擇市縣",
        "district": "請選擇區域",
        "locationSet": "請設置天氣數據采集地域",
        "columns": "列名",
        "color": "顏色",
        "bleTarget": "藍牙目標",
        "blue": "藍色",
        "green": "綠色",
        "cyan": "青色",
        "red": "紅色",
        "yellow": "黃色",
        "gray": "灰色",
        "columnsSet": "請設置列名",
        "displayRange": "指示範圍",
        "mod5": "取值範圍的極差必須為5的正整數倍。",
        "displayText": "顯示文本",
        "imageURL": "圖片鏈接",
        "saveSuccess": "項目保存成功",
        "saveFail": "項目保存失敗 ",
        "info": "提示信息",
        "confirmDel": "確定刪除項目",
        "confirm": "確定",
        "deleting": "刪除中...",
        "error": "錯誤信息",
        "deleteFail": "刪除失敗",
        "cancel": "取消",
        "createPrj": "創建一個項目",
        "createPrjName": "請輸入新項目名稱",
        "import": "導入一個項目",
        "importData": "匯入用戶數據",
        "importDataWarning": "同名項目將被覆蓋，請謹慎操作",
        "inputAuCode": "請輸入項目授權碼",
        "invalidAU": "項目授權碼無效（或已失效）",
        "incorrectAU": "項目授權碼格式不正確",
        "speedLimit": "發送數據頻率過高，已進行限製。",
        "diffRepeat": "兩次輸入的密碼不一致",
        "userEmpty": "用戶名不能為空",
        "passEmpty": "密碼不能為空",
        "userExist": "用戶名已存在",
        "emailEmpty": "請輸入電子郵件地址",
        "querying": "查詢中...",
        "queryS": "查詢成功",
        "queryF": "查詢失敗",
        "queryN": "用戶不存在",
        "answerEmpty": "答案不能為空！",
        "resetSuccess": "密碼重置成功",
        "wrongAns": "答案錯誤",
        "shareAt": "分享於",
        "invalidAUPrj": "授權項目不存在或已失效。",
        "clearData": "清除數據",
        "confirmClear": "確認清除",
        'prjs': "項目中的",
        'clearAsk': "條離線存儲數據嗎？",
        "clearS": "清除成功",
        "guide": "使用指南",
        "settingP": "設置中...",
        "settingS": "設置成功",
        "settingF": "設置失敗",
        "option": "選項",
        "noData": "暫無數據",
        "updating": "更新中...",
        "updateF": "更新失敗",
        "mapJSON": "一個地圖組件收到了無效的JSON消息。",
        "invalidUType": "不正確的組件類別。",
        "noUnitFound": "未找到組件。",
        "platformList": "已登錄平台",
        "deviceList": "已連接設備",
        "camera": "攝像頭",
        "mic": "麥克風",
        "tinydb": "下拉選項",
        "resolution": "分辨率",
        "fps": "幀率",
        'tdb': "TinyDB"
    },
    "en": {
        "beepAudio": "Alert Sound",
        "tensorAI": "- Artificial Intelligence -",
        "imageNet": "ImageNet Image Classification",
        "cocoSSD": "CocoSSD Object Detection",
        "deepLab": "DeepLab Image Segmentation",
        "blazeFace": "Face Detection",
        "mediaPipe": "Gesture Detection",
        "ocr": "Buzzer",
        "qr": "QR Code Recognition",
        "coco": "Object Recognition",
        "MoveNet": "MoveNet Pose Detection",
        "Bert": "Text Question Answering",
        "SpeechCMD": "SpeechCMD Voice Commands",
        "syncInterval": "Automatic Update Interval",
        "sendInterval": "Automatic Send Interval",
        "never": "Never",
        "i1min": "Every minute",
        "i3min": "Every 3 minutes",
        "i5min": "Every 5 minutes",
        "i10min": "Every 10 minutes",
        "i15min": "Every 15 minutes",
        "i30min": "Every 30 minutes",
        "i60min": "Every 60 minutes",
        "dstTopicLenIllegal": "Action topic cannot be empty",
        "dstMessageLenIllegal": "Action message cannot be empty",
        "conditionLenIllegal": "Condition value cannot be empty",
        "srcTopic": "Condition Topic",
        "condition": "Condition",
        "conditionRelation": "Condition Relationship",
        "dstTopic": "Action Topic",
        "dstMessage": "Action Message",
        "invalidContent": "Invalid data content",
        "backRun": "Run data view & logic view in the background",
        "stopBackRun": "Stop running this project in the background",
        "backRunErr": "An error occurred while running in the background",
        "editProper": "Modify properties",
        "viewProject": "View & edit project",
        "illegalCycle": "Loop method detected in the logic view. It is not allowed to run in the background",
        "codeException": "The logic view contains code that cannot run in the background",
        "loading": "Loading",
        "loading2": "Processing",
        "wrongAcc": "Incorrect email address or password",
        "noKey": "Please enter the Mixly Key",
        "noVfCode": "Please enter the project authorization code",
        "modify": "Modify ",
        "rename": "Rename",
        "copy": "Copy",
        "share": "Share",
        "delete": "Delete",
        "renamePrj": "Rename project",
        "triggerTopic": "Trigger topic",
        "triggerMessage": "Trigger content",
        "triggerInterval": "Trigger Interval (ms)",
        "triggerTimes": "Times Limit (0-Unlimited)",
        "newPrjName": "New name",
        "lengthRes": "The length of the project name should be between 3 and 10 characters",
        "prjExist": "A project with the same name already exists",
        "copyName": "Copy name",
        "prjOverflow": "You have reached the maximum number of projects",
        "shareConfirm": "Enable sharing for this project? Anyone with the authorization code can access or copy it.",
        "shareSuccess": "Project sharing enabled",
        "aucode": "Authorization Code",
        "guestURL": "URL for guests",
        "logicError": "An error occurred in the logical view, please modify it.",
        "prjManage": "Project Management",
        "blocklyDev": "Blockly mode is under development.",
        "hardwarePass": "Connection Settings",
        "connected": "Connected to server",
        "connectCount": " device(s) connected",
        "connecting": "Connecting server...",
        "disconnected": "Disconnected",
        "pauseBeforeModify": "To modify the code, pause the project first.",
        "console": "Output",
        "downloading": "Downloading project data...",
        "prj404": "This project does not exist!",
        "slow": "Slow rendering detected",
        "remindClear": ", it may be caused by too much data in the data view. Please clear the useless data in time.",
        "duringOff": "During offline, the project received ",
        "messageRem": " messages.<br>These messages have been saved in the data view.",
        "topic": "Topic",
        "message": "Message",
        "time": "Time",
        "listener": "Listen Topic: ",
        "select": "Please select",
        "monitor": "Data Monitor",
        "download": "Download Data",
        "clear": "Clear Current Data",
        "clearAll": "Remove Current Topic",
        "rtchart": "Real-time Chart",
        "sender": "Send Topic: ",
        "value": "Value",
        "noData": "No Data",
        "sendString": "Send Text",
        "topicUnset": "Please set a topic before sending.",
        "sendJSON": "Send JSON",
        "key": "Key",
        "JSONempty": "The JSON message must contain at least one key-value pair",
        "addKey": "Add Key",
        "invalidJSON": "Invalid content to send",
        "control": "- Control -",
        "switch": "Switch",
        "button": "Button",
        "slider": "Slider",
        "joystick": "Joystick",
        "RGB": "RGB Picker",
        "bulb": "Bulb",
        "timer": "Timer Trigger",
        "trigger": "Condition Trigger",
        "magic": "Decorative Panel",
        "pixel": "Pixel Display",
        "video": "Video",
        "widget": "Widget",
        "data": "- Data -",
        "lineChart": "Line Chart",
        "barChart": "Bar Chart",
        "dataTable": "Data Table",
        "dataMap": "Map",
        "dashboard": "Dashboard",
        "weather": "Live Weather",
        "text": "- Media -",
        "keyboard": "Text Input",
        "screen": "Text Screen",
        "decorate": "- Decoration -",
        "label": "Label",
        "picture": "Image / Video",
        "ble": "Bluetooth Adapter",
        "unitName": "Unit Name",
        "messTopic": "Message Topic",
        "options": "Options (comma separated)",
        "readMessTopic": "Read Message Topic",
        "writeMessTopic": "Write Message Topic",
        "feedbackMode": "Feedback Mode",
        "sameUnit": "A unit having the same name already exists.",
        "nameLenIllegal": "The component name must be 1–10 characters long.",
        "topicLenIllegal": "The message topic must be 1–10 characters long.",
        "messageLenIllegal": "Message content cannot be empty",
        "illegalInterval": "The minimum trigger interval is 500 ms",
        "illegalTimes": "The trigger count must be a non-negative integer",
        "invalidSlideRange": "Invalid slide range.",
        "invalidPixel": "Invalid pixel matrix.",
        "slideRange": "Value Range",
        "hideTitle": "Inner Title",
        "min": "Minimum",
        "max": "Maximum",
        "step": "Step",
        "xpixel": "X Pixel",
        "ypixel": "Y Pixel",
        "show": "Show",
        "hide": "Hide",
        "choicesList": "Choices List",
        "recvMode": "Selection Mode",
        "single": "Single",
        "multiple": "Multiple",
        "listEmpty": "Choices list can not be empty",
        "location": "Location",
        "province": "Province",
        "city": "City",
        "district": "District",
        "locationSet": "Please select a location",
        "columns": "Columns",
        "color": "Color",
        "bleTarget": "Bluetooth Device",
        "blue": "Blue",
        "green": "Green",
        "cyan": "Cyan",
        "red": "Red",
        "yellow": "Yellow",
        "gray": "Gray",
        "columnsSet": "Please set at least 1 column",
        "displayRange": "Display Range",
        "mod5": "The range of values must be a positive integer multiple of 5.",
        "displayText": "Display Text",
        "imageURL": "Image URL",
        "saveSuccess": "Project saved successfully",
        "saveFail": "Failed to save the project",
        "info": "Warning",
        "confirmDel": "Confirm to delete project ",
        "confirm": "Confirm",
        "deleting": "Deleting...",
        "error": "Error",
        "deleteFail": "Delete failed",
        "cancel": "Cancel",
        "createPrj": "New Project",
        "createPrjName": "Project Name",
        "import": "Import Project",
        "importData": "Import User Data",
        "importDataWarning": "Projects with the same name will be overwritten, so proceed with caution",
        "inputAuCode": "Authorization Code",
        "invalidAU": "Invalid Authorization Code",
        "incorrectAU": "Incorrect Authorization Code",
        "speedLimit": "The frequency of sending data is too high and has been limited.",
        "diffRepeat": "The passwords do not match",
        "userEmpty": "Email address cannot be empty",
        "passEmpty": "Password cannot be empty",
        "userExist": "This email address is already registered",
        "emailEmpty": "Please enter an email address",
        "querying": "Querying...",
        "queryS": "Query successful",
        "queryF": "Query failed",
        "queryN": "User does not exist",
        "answerEmpty": "Answer cannot be empty",
        "resetSuccess": "Password reset successfully",
        "wrongAns": "Incorrect answer",
        "shareAt": " shared at ",
        "invalidAUPrj": "Invalid Authorization Code",
        "clearData": "Clear Data",
        "confirmClear": "Confirm to clear ",
        'prjs': ": ",
        'clearAsk': " reserved offline messages?",
        "clearS": "Data cleared successfully",
        "guide": "Guide",
        "settingP": "Saving...",
        "settingS": "Settings saved",
        "settingF": "Failed to save settings",
        "option": "Option",
        "noData": "No Data",
        "updating": "Updating...",
        "updateF": "Update Failed",
        "mapJSON": "A map unit received an invalid JSON message.",
        "invalidUType": "Invalid unit type.",
        "noUnitFound": "The component does not exist.",
        "platformList": "Platforms",
        "deviceList": "Devices",
        "camera": "Camera",
        "mic": "Microphone",
        "tinydb": "Options",
        "resolution": "Resolution",
        "fps": "FPS",
        'tdb': "TinyDB"
    }
}

// Translations shared by recently added pages and dynamic UI fragments.
// Keeping these keys in the same dictionary lets static markup and JavaScript
// use one lookup function without changing the existing page structure.
var JSLangExtensions = {
    "zh": {
        "adminLogin": "登录管理后台",
        "managePageTitle": "MixIO 管理后台",
        "editorPageTitle": "文档编辑 - MixIO CoDrive",
        "adminAccount": "管理员账号",
        "adminPassword": "管理员密码",
        "filterTopic": "筛选主题",
        "filterTimeRange": "筛选时间范围",
        "storageSpace": "存储空间",
        "noWebBluetooth": "当前浏览器不支持 Web Bluetooth，请使用最新版 Chrome 或 Edge。",
        "credentialsCopied": "凭据信息已复制到剪贴板",
        "privateCredential": "私有凭证",
        "projectAuthorizationCode": "项目授权码",
        "projectNotShared": "项目尚未启用共享授权",
        "loadingLogicEngine": "正在加载逻辑引擎...",
        "guideLabel": "入门指南",
        "desiredTopic": "要获取的主题",
        "desiredMessageCount": "要获取的最新消息数量",
        "apiRefreshHint": "数据通常每 30 秒更新一次；手动保存项目会立即更新。",
        "httpApiDataTitle": "通过 HTTP API 获取数据",
        "none": "无",
        "by": "按",
        "groupedDisplay": "分组显示",
        "clearAfterSend": "发送后清空",
        "weakAlert": "弱提示音",
        "strongAlert": "强提示音",
        "alarmSound": "警报音",
        "realTime": "实时时间",
        "randomInteger": "随机整数（1–99）",
        "greaterThan": "大于",
        "greaterThanOrEqual": "大于等于",
        "lessThan": "小于",
        "lessThanOrEqual": "小于等于",
        "equal": "等于",
        "notEqual": "不等于",
        "errorOccurred": "出错了",
        "backgroundRunErrorDetails": "项目在后台运行期间发生了以下错误",
        "autoSaveStorageHint": "所有以 $ 开头的主题中的消息和图片都会自动保存",
        "observeStorageHint": "所有发送到 /storage 主题的消息和图片都会自动保存",
        "date": "日期",
        "deleteSelected": "删除选中项",
        "downloadSelected": "下载选中项",
        "tileView": "平铺视图",
        "listView": "列表视图",
        "confirmDeleteSelected": "确定要删除选中的 {{count}} 个文件吗？",
        "noStoredFiles": "暂无存储文件",
        "textFile": "文本",
        "selectItem": "选择",
        "confirmDeleteFile": "确定要删除此文件吗？",
        "loadingMapEngine": "正在加载地图引擎...",
        "loadingAiEngine": "正在加载 AI 引擎...",
        "addCurrentFace": "添加当前人脸数据",
        "faceSaved": "人脸数据已保存",
        "noFaceDetected": "未检测到人脸",
        "uploadFaceImage": "上传人脸图片",
        "personName": "人物命名",
        "noCodeDetected": "未检测到二维码或条形码",
        "unitTitle": "组件标题",
        "backgroundColor": "背景颜色",
        "titleColor": "标题颜色",
        "dataView": "数据",
        "componentView": "组件",
        "platformType": "平台类型",
        "mixioVersion": "MixIO 版本号",
        "mixlyServerVersion": "Mixly 编程服务器版本号",
        "serverClock": "服务器时钟",
        "updateMixioServer": "更新 MixIO 服务器",
        "updateMixlyServer": "更新 Mixly 编程服务器",
        "configItem": "配置项",
        "description": "含义",
        "dataType": "数据类型",
        "configHttpPort": "HTTP 端口",
        "configHttpsPort": "HTTPS 端口",
        "configPrivateKey": "私钥路径或网址",
        "configCertificate": "证书路径或网址",
        "configMqttPort": "MQTT 端口",
        "configMqttWsPort": "MQTT WebSocket 端口",
        "configMqttWssPort": "MQTT 安全 WebSocket 端口",
        "configYjsWsPort": "协同编辑 WebSocket 端口",
        "configYjsWssPort": "协同编辑安全 WebSocket 端口",
        "configMaxProjects": "每位用户的项目数量上限",
        "configMaxOfflineMessages": "每位用户的离线消息存储上限",
        "configMaxMessagesPerSecond": "每位用户每秒可发送的消息上限",
        "configAllowRegister": "允许用户自主注册",
        "configAllowOfflineStorage": "允许离线存储消息",
        "configOfflineMode": "禁用天气和地图数据",
        "configBaiduClientAk": "百度地图客户端应用 AK",
        "configBaiduServerAk": "百度地图服务端应用 AK",
        "configTencentKey": "腾讯地图密钥",
        "configAnalyticsLink": "百度统计链接",
        "configAdminUser": "管理后台用户名",
        "configAdminPassword": "管理后台密码",
        "configStorageEngine": "数据库引擎",
        "configMysqlHost": "MySQL 地址",
        "configMysqlPort": "MySQL 端口",
        "configMysqlUser": "MySQL 用户名",
        "configMysqlPassword": "MySQL 密码",
        "configMysqlDatabase": "MySQL 数据库名",
        "configFooter": "首页显示的备案信息",
        "yes": "是",
        "no": "否",
        "saveSettingsRestart": "保存设置并重新启动",
        "batchAccountFormat": "格式（每个账号一行）：账号,密码,密保问题,问题答案",
        "addAccounts": "确认添加",
        "user": "用户",
        "clearMessages": "清空消息",
        "resetPassword": "重置密码",
        "deleteUser": "删除用户",
        "projectCount": "项目数",
        "messageCount": "消息量",
        "actions": "操作",
        "actionSuccess": "操作成功",
        "actionFailed": "操作失败",
        "resetUserPasswordConfirm": "确定要将用户“{{user}}”的密码重置为“123456”吗？",
        "deleteUserConfirm": "确定要删除用户“{{user}}”吗？此操作无法撤销。",
        "resettingPassword": "正在重置密码...",
        "settingsSavedRestarting": "保存成功，正在重新启动服务器。",
        "abnormalStatus": "状态异常",
        "updateCompletedRestart": "更新已完成，请手动重新启动 MixIO 服务。",
        "updateCompleted": "更新已完成",
        "sendingUpdateRequest": "正在发送更新请求...",
        "localVersion": "本地版本：{{version}}",
        "cloudVersion": "云端版本：{{version}}",
        "updateRequired": "需要更新：{{value}}",
        "downloadStarted": "开始下载...",
        "downloadingProgress": "下载中：{{progress}}%",
        "extracting": "正在解压...",
        "extractionCompleteWait": "{{version}} 解压完成，正在清理缓存，约需 30 秒...",
        "downloadFailedExit": "下载失败，5 秒后自动退出...",
        "upToDateExit": "当前已是最新版本，5 秒后自动退出...",
        "invalidFormat": "格式不正确",
        "userAlreadyExists": "用户已存在",
        "connectionFailed": "连接失败",
        "batchResult": "成功：{{success}}；失败：{{failed}}；失败原因：{{reasons}}",
        "newFile": "新建文件",
        "document": "文档",
        "spreadsheet": "表格",
        "image": "图片",
        "file": "文件",
        "importFile": "导入文件",
        "listViewHint": "列表视图 · 点击行可编辑",
        "fileName": "文件名",
        "enterFileName": "请输入文件名",
        "create": "创建",
        "confirmDelete": "确认删除",
        "deleteFileQuestion": "确定要删除文件“{{name}}”吗？",
        "irreversible": "此操作无法撤销",
        "processing": "处理中...",
        "unknown": "未知",
        "downloadSuccess": "下载成功：{{name}}",
        "fileDownloadFailed": "文件下载失败",
        "loadFileListFailed": "加载文件列表失败",
        "loadFileListNetworkFailed": "加载文件列表失败，请检查网络连接",
        "noFiles": "暂无文件",
        "noFilesHint": "点击“新建文件”或“导入文件”开始使用协作云盘",
        "type": "类型",
        "modifiedAt": "修改时间",
        "size": "大小",
        "edit": "编辑",
        "favoriteSharedFiles": "收藏的共享文件",
        "favoriteSharedFilesHint": "（来自他人的分享链接）",
        "from": "来自",
        "favoritedAt": "收藏时间",
        "status": "状态",
        "shared": "共享",
        "available": "可用",
        "unavailable": "已失效",
        "unfavorite": "取消收藏",
        "sourceFileUnavailable": "原文件已失效，无法编辑",
        "imageOnlineEditUnsupported": "图片文件不支持在线编辑",
        "confirmUnfavorite": "确定要取消收藏“{{name}}”吗？",
        "shareLink": "分享链接",
        "shareLinkHelp": "分享此链接，即可与他人协同编辑文档“{{name}}”。",
        "copy": "复制",
        "copied": "已复制",
        "copiedToClipboard": "链接已复制到剪贴板",
        "anyoneCanEdit": "任何获得此链接的人都可以查看和编辑文档",
        "close": "关闭",
        "unfavoriteSuccess": "已取消收藏",
        "unfavoriteFailed": "取消收藏失败",
        "fileDeleteSuccess": "文件删除成功",
        "fileDeleteFailed": "删除文件失败，请稍后重试",
        "newDocument": "新建文档",
        "newSpreadsheet": "新建表格",
        "markdownExtensionHint": "将自动为文件名添加 .md 扩展名",
        "csvExtensionHint": "将自动为文件名添加 .csv 扩展名",
        "fileCreated": "已创建{{type}}：{{name}}",
        "createFileFailed": "创建文件失败",
        "createFileRetry": "创建文件失败，请稍后重试",
        "convertedAndUploaded": "转换并上传成功：{{name}}",
        "uploadFailed": "上传失败",
        "fileUploadFailed": "文件上传失败",
        "excelConversionFailed": "Excel 文件转换失败，请检查文件格式",
        "docxConversionFailed": "DOCX 文件转换失败，请检查文件格式",
        "docxReadFailed": "DOCX 文件读取失败，请检查文件格式",
        "uploadSuccess": "上传成功：{{name}}（{{type}}）",
        "tinydbManagement": "TinyDB 数据管理",
        "dataList": "数据列表",
        "refresh": "刷新",
        "add": "新增",
        "search": "搜索",
        "tag": "标签",
        "showingFrom": "显示第",
        "to": "到",
        "totalRecords": "条，共",
        "records": "条记录",
        "searchData": "搜索数据",
        "tagKeyword": "标签关键字",
        "enterTagKeyword": "输入标签关键字",
        "returnType": "返回类型",
        "tagAndValue": "标签和值",
        "tagsOnly": "仅标签",
        "valuesOnly": "仅值",
        "resultLimit": "返回数量",
        "inputTag": "输入标签",
        "inputValue": "输入值",
        "save": "保存",
        "unsavedNewData": "请先保存或取消当前新增的数据",
        "tagRequired": "标签不能为空",
        "valueRequired": "值不能为空",
        "dataAddSuccess": "数据添加成功",
        "addFailed": "添加失败：{{message}}",
        "networkError": "网络错误，请稍后重试",
        "userInfoMissing": "未找到用户信息，请重新登录",
        "loadDataFailed": "加载数据失败：{{message}}",
        "dataUpdateSuccess": "数据更新成功",
        "updateFailed": "更新失败：{{message}}",
        "deleteTagConfirm": "确定要删除标签“{{tag}}”的数据吗？",
        "previousPage": "上一页",
        "nextPage": "下一页",
        "dataDeleteSuccess": "数据删除成功",
        "deleteFailedWithMessage": "删除失败：{{message}}",
        "searchComplete": "搜索完成",
        "searchFailed": "搜索失败：{{message}}",
        "back": "返回",
        "sharedBy": "来自 {{user}}",
        "saveToMyDrive": "收藏到我的云盘",
        "versions": "版本",
        "saved": "已保存",
        "disconnectedStatus": "已断开",
        "addRow": "添加行",
        "addColumn": "添加列",
        "deleteRow": "删除行",
        "deleteColumn": "删除列",
        "onlineCollaboration": "在线协同",
        "fileVersionHistory": "文件版本历史",
        "loadVersionsFailed": "加载版本列表失败",
        "noVersionHistory": "暂无版本历史",
        "versionHistoryHint": "保存文档后，系统将自动记录版本历史",
        "createdBy": "由 {{user}} 创建",
        "view": "查看",
        "restore": "恢复",
        "currentVersion": "当前版本",
        "versionPreview": "版本预览",
        "restoreThisVersion": "恢复此版本",
        "getVersionFailed": "获取版本内容失败",
        "confirmRestoreVersion": "确定要恢复到此版本吗？当前内容将被覆盖。",
        "versionRestoreSuccess": "版本恢复成功",
        "contentUpdated": "内容已更新",
        "restoreVersionFailed": "恢复版本失败",
        "confirmDeleteVersion": "确定要删除此版本吗？此操作无法撤销。",
        "versionDeleteSuccess": "版本删除成功",
        "deleteVersionFailed": "删除版本失败",
        "saving": "保存中...",
        "saveFailed": "保存失败",
        "fileNameRequired": "文件名不能为空",
        "renameSuccess": "重命名成功",
        "renameFailed": "重命名失败",
        "documentEditorTitle": "{{name}} - 文档编辑",
        "spreadsheetEditorTitle": "{{name}} - 表格编辑",
        "collaborationConnected": "协同编辑已连接",
        "collaborationDisconnected": "协同编辑连接已断开，将使用本地模式",
        "collaboratorJoined": "有协作者加入",
        "collaborationUnavailable": "协同编辑不可用，将使用普通模式",
        "uploadingImage": "正在上传图片...",
        "imageUploadSuccess": "图片上传成功",
        "imageUploadFailed": "图片上传失败",
        "uploadImage": "上传图片",
        "textColor": "文字颜色",
        "keepOneRow": "至少保留一行",
        "keepOneColumn": "至少保留一列",
        "csvFormatSuccess": "CSV 格式化完成",
        "csvFormatFailed": "CSV 格式化失败",
        "fileLoaded": "{{type}}加载成功",
        "loadFailed": "加载失败",
        "loadDocumentFailed": "加载文档失败",
        "unsavedLeaveConfirm": "文档尚未保存，确定要离开吗？",
        "missingParameters": "缺少必要参数",
        "unsupportedEditType": "仅支持编辑文档和表格文件",
        "favoritedToDrive": "已收藏到我的云盘",
        "favorited": "已收藏",
        "favoriteFailed": "收藏失败",
        "you": "你",
        "editingOnline": "在线编辑",
        "unsaved": "未保存",
        "chooseTextColor": "选择文字颜色",
        "customColor": "自定义颜色：",
        "editorPlaceholder": "在此编写文档内容...",
        "connectedStatus": "已连接",
        "connectingStatus": "连接中...",
        "syncedStatus": "已同步",
        "unknownStatus": "未知状态",
        "justNow": "刚刚",
        "minutesAgo": "{{count}} 分钟前",
        "hoursAgo": "{{count}} 小时前",
        "daysAgo": "{{count}} 天前"
    },
    "tw": {
        "adminLogin": "登入管理後台",
        "managePageTitle": "MixIO 管理後台",
        "editorPageTitle": "文件編輯 - MixIO CoDrive",
        "adminAccount": "管理員帳號",
        "adminPassword": "管理員密碼",
        "filterTopic": "篩選主題",
        "filterTimeRange": "篩選時間範圍",
        "storageSpace": "儲存空間",
        "noWebBluetooth": "目前的瀏覽器不支援 Web Bluetooth，請使用最新版 Chrome 或 Edge。",
        "credentialsCopied": "憑證資訊已複製到剪貼簿",
        "privateCredential": "私密憑證",
        "projectAuthorizationCode": "專案授權碼",
        "projectNotShared": "專案尚未啟用共享授權",
        "loadingLogicEngine": "正在載入邏輯引擎...",
        "guideLabel": "入門指南",
        "desiredTopic": "要取得的主題",
        "desiredMessageCount": "要取得的最新訊息數量",
        "apiRefreshHint": "資料通常每 30 秒更新一次；手動儲存專案會立即更新。",
        "httpApiDataTitle": "透過 HTTP API 取得資料",
        "none": "無",
        "by": "依",
        "groupedDisplay": "分組顯示",
        "clearAfterSend": "傳送後清除",
        "weakAlert": "弱提示音",
        "strongAlert": "強提示音",
        "alarmSound": "警報音",
        "realTime": "即時時間",
        "randomInteger": "隨機整數（1–99）",
        "greaterThan": "大於",
        "greaterThanOrEqual": "大於或等於",
        "lessThan": "小於",
        "lessThanOrEqual": "小於或等於",
        "equal": "等於",
        "notEqual": "不等於",
        "errorOccurred": "發生錯誤",
        "backgroundRunErrorDetails": "專案在背景執行期間發生以下錯誤",
        "autoSaveStorageHint": "所有以 $ 開頭之主題中的訊息和圖片都會自動儲存",
        "observeStorageHint": "所有傳送到 /storage 主題的訊息和圖片都會自動儲存",
        "date": "日期",
        "deleteSelected": "刪除所選項目",
        "downloadSelected": "下載所選項目",
        "tileView": "並排檢視",
        "listView": "清單檢視",
        "confirmDeleteSelected": "確定要刪除所選的 {{count}} 個檔案嗎？",
        "noStoredFiles": "目前沒有儲存的檔案",
        "textFile": "文字",
        "selectItem": "選取",
        "confirmDeleteFile": "確定要刪除此檔案嗎？",
        "loadingMapEngine": "正在載入地圖引擎...",
        "loadingAiEngine": "正在載入 AI 引擎...",
        "addCurrentFace": "新增目前的人臉資料",
        "faceSaved": "人臉資料已儲存",
        "noFaceDetected": "未偵測到人臉",
        "uploadFaceImage": "上傳人臉圖片",
        "personName": "人物命名",
        "noCodeDetected": "未偵測到 QR Code 或條碼",
        "unitTitle": "元件標題",
        "backgroundColor": "背景顏色",
        "titleColor": "標題顏色",
        "dataView": "資料",
        "componentView": "元件",
        "platformType": "平台類型",
        "mixioVersion": "MixIO 版本",
        "mixlyServerVersion": "Mixly 程式伺服器版本",
        "serverClock": "伺服器時間",
        "updateMixioServer": "更新 MixIO 伺服器",
        "updateMixlyServer": "更新 Mixly 程式伺服器",
        "configItem": "設定項目",
        "description": "說明",
        "dataType": "資料類型",
        "configHttpPort": "HTTP 連接埠",
        "configHttpsPort": "HTTPS 連接埠",
        "configPrivateKey": "私密金鑰路徑或網址",
        "configCertificate": "憑證路徑或網址",
        "configMqttPort": "MQTT 連接埠",
        "configMqttWsPort": "MQTT WebSocket 連接埠",
        "configMqttWssPort": "MQTT 安全 WebSocket 連接埠",
        "configYjsWsPort": "協同編輯 WebSocket 連接埠",
        "configYjsWssPort": "協同編輯安全 WebSocket 連接埠",
        "configMaxProjects": "每位使用者的專案數量上限",
        "configMaxOfflineMessages": "每位使用者的離線訊息儲存上限",
        "configMaxMessagesPerSecond": "每位使用者每秒可傳送的訊息上限",
        "configAllowRegister": "允許使用者自行註冊",
        "configAllowOfflineStorage": "允許離線儲存訊息",
        "configOfflineMode": "停用天氣與地圖資料",
        "configBaiduClientAk": "百度地圖用戶端應用程式 AK",
        "configBaiduServerAk": "百度地圖伺服器端應用程式 AK",
        "configTencentKey": "騰訊地圖金鑰",
        "configAnalyticsLink": "百度統計連結",
        "configAdminUser": "管理後台使用者名稱",
        "configAdminPassword": "管理後台密碼",
        "configStorageEngine": "資料庫引擎",
        "configMysqlHost": "MySQL 位址",
        "configMysqlPort": "MySQL 連接埠",
        "configMysqlUser": "MySQL 使用者名稱",
        "configMysqlPassword": "MySQL 密碼",
        "configMysqlDatabase": "MySQL 資料庫名稱",
        "configFooter": "首頁顯示的備案資訊",
        "yes": "是",
        "no": "否",
        "saveSettingsRestart": "儲存設定並重新啟動",
        "batchAccountFormat": "格式（每個帳號一行）：帳號,密碼,安全問題,問題答案",
        "addAccounts": "確認新增",
        "user": "使用者",
        "clearMessages": "清除訊息",
        "resetPassword": "重設密碼",
        "deleteUser": "刪除使用者",
        "projectCount": "專案數",
        "messageCount": "訊息量",
        "actions": "操作",
        "actionSuccess": "操作成功",
        "actionFailed": "操作失敗",
        "resetUserPasswordConfirm": "確定要將使用者「{{user}}」的密碼重設為「123456」嗎？",
        "deleteUserConfirm": "確定要刪除使用者「{{user}}」嗎？此操作無法復原。",
        "resettingPassword": "正在重設密碼...",
        "settingsSavedRestarting": "儲存成功，正在重新啟動伺服器。",
        "abnormalStatus": "狀態異常",
        "updateCompletedRestart": "更新已完成，請手動重新啟動 MixIO 服務。",
        "updateCompleted": "更新已完成",
        "sendingUpdateRequest": "正在傳送更新要求...",
        "localVersion": "本機版本：{{version}}",
        "cloudVersion": "雲端版本：{{version}}",
        "updateRequired": "需要更新：{{value}}",
        "downloadStarted": "開始下載...",
        "downloadingProgress": "下載中：{{progress}}%",
        "extracting": "正在解壓縮...",
        "extractionCompleteWait": "{{version}} 解壓縮完成，正在清除快取，約需 30 秒...",
        "downloadFailedExit": "下載失敗，5 秒後自動退出...",
        "upToDateExit": "目前已是最新版本，5 秒後自動退出...",
        "invalidFormat": "格式不正確",
        "userAlreadyExists": "使用者已存在",
        "connectionFailed": "連線失敗",
        "batchResult": "成功：{{success}}；失敗：{{failed}}；失敗原因：{{reasons}}",
        "newFile": "新增檔案",
        "document": "文件",
        "spreadsheet": "試算表",
        "image": "圖片",
        "file": "檔案",
        "importFile": "匯入檔案",
        "listViewHint": "清單檢視 · 點選資料列即可編輯",
        "fileName": "檔案名稱",
        "enterFileName": "請輸入檔案名稱",
        "create": "建立",
        "confirmDelete": "確認刪除",
        "deleteFileQuestion": "確定要刪除檔案「{{name}}」嗎？",
        "irreversible": "此操作無法復原",
        "processing": "處理中...",
        "unknown": "未知",
        "downloadSuccess": "下載成功：{{name}}",
        "fileDownloadFailed": "檔案下載失敗",
        "loadFileListFailed": "載入檔案清單失敗",
        "loadFileListNetworkFailed": "載入檔案清單失敗，請檢查網路連線",
        "noFiles": "目前沒有檔案",
        "noFilesHint": "點選「新增檔案」或「匯入檔案」開始使用協作雲端硬碟",
        "type": "類型",
        "modifiedAt": "修改時間",
        "size": "大小",
        "edit": "編輯",
        "favoriteSharedFiles": "已收藏的共享檔案",
        "favoriteSharedFilesHint": "（來自他人的共享連結）",
        "from": "來源",
        "favoritedAt": "收藏時間",
        "status": "狀態",
        "shared": "共享",
        "available": "可使用",
        "unavailable": "已失效",
        "unfavorite": "取消收藏",
        "sourceFileUnavailable": "原始檔案已失效，無法編輯",
        "imageOnlineEditUnsupported": "圖片檔案不支援線上編輯",
        "confirmUnfavorite": "確定要取消收藏「{{name}}」嗎？",
        "shareLink": "共享連結",
        "shareLinkHelp": "分享此連結，即可與他人協同編輯文件「{{name}}」。",
        "copy": "複製",
        "copied": "已複製",
        "copiedToClipboard": "連結已複製到剪貼簿",
        "anyoneCanEdit": "任何取得此連結的人都可以檢視及編輯文件",
        "close": "關閉",
        "unfavoriteSuccess": "已取消收藏",
        "unfavoriteFailed": "取消收藏失敗",
        "fileDeleteSuccess": "檔案刪除成功",
        "fileDeleteFailed": "刪除檔案失敗，請稍後再試",
        "newDocument": "新增文件",
        "newSpreadsheet": "新增試算表",
        "markdownExtensionHint": "將自動為檔案名稱加上 .md 副檔名",
        "csvExtensionHint": "將自動為檔案名稱加上 .csv 副檔名",
        "fileCreated": "已建立{{type}}：{{name}}",
        "createFileFailed": "建立檔案失敗",
        "createFileRetry": "建立檔案失敗，請稍後再試",
        "convertedAndUploaded": "轉換並上傳成功：{{name}}",
        "uploadFailed": "上傳失敗",
        "fileUploadFailed": "檔案上傳失敗",
        "excelConversionFailed": "Excel 檔案轉換失敗，請檢查檔案格式",
        "docxConversionFailed": "DOCX 檔案轉換失敗，請檢查檔案格式",
        "docxReadFailed": "DOCX 檔案讀取失敗，請檢查檔案格式",
        "uploadSuccess": "上傳成功：{{name}}（{{type}}）",
        "tinydbManagement": "TinyDB 資料管理",
        "dataList": "資料清單",
        "refresh": "重新整理",
        "add": "新增",
        "search": "搜尋",
        "tag": "標籤",
        "showingFrom": "顯示第",
        "to": "至",
        "totalRecords": "筆，共",
        "records": "筆記錄",
        "searchData": "搜尋資料",
        "tagKeyword": "標籤關鍵字",
        "enterTagKeyword": "輸入標籤關鍵字",
        "returnType": "回傳類型",
        "tagAndValue": "標籤和值",
        "tagsOnly": "僅標籤",
        "valuesOnly": "僅值",
        "resultLimit": "回傳數量",
        "inputTag": "輸入標籤",
        "inputValue": "輸入值",
        "save": "儲存",
        "unsavedNewData": "請先儲存或取消目前新增的資料",
        "tagRequired": "標籤不得為空",
        "valueRequired": "值不得為空",
        "dataAddSuccess": "資料新增成功",
        "addFailed": "新增失敗：{{message}}",
        "networkError": "網路錯誤，請稍後再試",
        "userInfoMissing": "找不到使用者資訊，請重新登入",
        "loadDataFailed": "載入資料失敗：{{message}}",
        "dataUpdateSuccess": "資料更新成功",
        "updateFailed": "更新失敗：{{message}}",
        "deleteTagConfirm": "確定要刪除標籤「{{tag}}」的資料嗎？",
        "previousPage": "上一頁",
        "nextPage": "下一頁",
        "dataDeleteSuccess": "資料刪除成功",
        "deleteFailedWithMessage": "刪除失敗：{{message}}",
        "searchComplete": "搜尋完成",
        "searchFailed": "搜尋失敗：{{message}}",
        "back": "返回",
        "sharedBy": "來自 {{user}}",
        "saveToMyDrive": "收藏到我的雲端硬碟",
        "versions": "版本",
        "saved": "已儲存",
        "disconnectedStatus": "已中斷連線",
        "addRow": "新增資料列",
        "addColumn": "新增欄",
        "deleteRow": "刪除資料列",
        "deleteColumn": "刪除欄",
        "onlineCollaboration": "線上協作",
        "fileVersionHistory": "檔案版本記錄",
        "loadVersionsFailed": "載入版本清單失敗",
        "noVersionHistory": "目前沒有版本記錄",
        "versionHistoryHint": "儲存文件後，系統將自動記錄版本",
        "createdBy": "由 {{user}} 建立",
        "view": "檢視",
        "restore": "還原",
        "currentVersion": "目前版本",
        "versionPreview": "版本預覽",
        "restoreThisVersion": "還原此版本",
        "getVersionFailed": "取得版本內容失敗",
        "confirmRestoreVersion": "確定要還原到此版本嗎？目前內容將被覆蓋。",
        "versionRestoreSuccess": "版本還原成功",
        "contentUpdated": "內容已更新",
        "restoreVersionFailed": "版本還原失敗",
        "confirmDeleteVersion": "確定要刪除此版本嗎？此操作無法復原。",
        "versionDeleteSuccess": "版本刪除成功",
        "deleteVersionFailed": "刪除版本失敗",
        "saving": "儲存中...",
        "saveFailed": "儲存失敗",
        "fileNameRequired": "檔案名稱不得為空",
        "renameSuccess": "重新命名成功",
        "renameFailed": "重新命名失敗",
        "documentEditorTitle": "{{name}} - 文件編輯",
        "spreadsheetEditorTitle": "{{name}} - 試算表編輯",
        "collaborationConnected": "協同編輯已連線",
        "collaborationDisconnected": "協同編輯連線已中斷，將使用本機模式",
        "collaboratorJoined": "有協作者加入",
        "collaborationUnavailable": "協同編輯無法使用，將使用一般模式",
        "uploadingImage": "正在上傳圖片...",
        "imageUploadSuccess": "圖片上傳成功",
        "imageUploadFailed": "圖片上傳失敗",
        "uploadImage": "上傳圖片",
        "textColor": "文字顏色",
        "keepOneRow": "至少保留一個資料列",
        "keepOneColumn": "至少保留一欄",
        "csvFormatSuccess": "CSV 格式化完成",
        "csvFormatFailed": "CSV 格式化失敗",
        "fileLoaded": "{{type}}載入成功",
        "loadFailed": "載入失敗",
        "loadDocumentFailed": "載入文件失敗",
        "unsavedLeaveConfirm": "文件尚未儲存，確定要離開嗎？",
        "missingParameters": "缺少必要參數",
        "unsupportedEditType": "僅支援編輯文件與試算表檔案",
        "favoritedToDrive": "已收藏到我的雲端硬碟",
        "favorited": "已收藏",
        "favoriteFailed": "收藏失敗",
        "you": "你",
        "editingOnline": "線上編輯",
        "unsaved": "尚未儲存",
        "chooseTextColor": "選擇文字顏色",
        "customColor": "自訂顏色：",
        "editorPlaceholder": "在此編寫文件內容...",
        "connectedStatus": "已連線",
        "connectingStatus": "連線中...",
        "syncedStatus": "已同步",
        "unknownStatus": "未知狀態",
        "justNow": "剛剛",
        "minutesAgo": "{{count}} 分鐘前",
        "hoursAgo": "{{count}} 小時前",
        "daysAgo": "{{count}} 天前"
    },
    "en": {
        "adminLogin": "Sign in to Admin Console",
        "managePageTitle": "MixIO Admin Console",
        "editorPageTitle": "Document Editor - MixIO CoDrive",
        "adminAccount": "Administrator account",
        "adminPassword": "Administrator password",
        "filterTopic": "Filter by topic",
        "filterTimeRange": "Filter by time range",
        "storageSpace": "Storage",
        "noWebBluetooth": "This browser does not support Web Bluetooth. Use the latest Chrome or Edge.",
        "credentialsCopied": "Credentials copied to the clipboard",
        "privateCredential": "Private Credential",
        "projectAuthorizationCode": "Project Authorization Code",
        "projectNotShared": "Sharing is not enabled for this project",
        "loadingLogicEngine": "Loading the logic engine...",
        "guideLabel": "Getting Started",
        "desiredTopic": "topic to retrieve",
        "desiredMessageCount": "number of recent messages to retrieve",
        "apiRefreshHint": "Data normally updates every 30 seconds. Saving the project updates it immediately.",
        "httpApiDataTitle": "Get Data Through the HTTP API",
        "none": "None",
        "by": "By",
        "groupedDisplay": "Group results",
        "clearAfterSend": "Clear after sending",
        "weakAlert": "Soft Alert",
        "strongAlert": "Loud Alert",
        "alarmSound": "Alarm",
        "realTime": "Current Time",
        "randomInteger": "Random Integer (1–99)",
        "greaterThan": "Greater than",
        "greaterThanOrEqual": "Greater than or equal to",
        "lessThan": "Less than",
        "lessThanOrEqual": "Less than or equal to",
        "equal": "Equal to",
        "notEqual": "Not equal to",
        "errorOccurred": "Something Went Wrong",
        "backgroundRunErrorDetails": "The following error occurred while the project was running in the background",
        "autoSaveStorageHint": "Messages and images under topics beginning with $ are saved automatically",
        "observeStorageHint": "Messages and images sent to the /storage topic are saved automatically",
        "date": "Date",
        "deleteSelected": "Delete Selected",
        "downloadSelected": "Download Selected",
        "tileView": "Tile View",
        "listView": "List View",
        "confirmDeleteSelected": "Delete the {{count}} selected files?",
        "noStoredFiles": "No stored files",
        "textFile": "Text",
        "selectItem": "Select",
        "confirmDeleteFile": "Delete this file?",
        "loadingMapEngine": "Loading the map engine...",
        "loadingAiEngine": "Loading the AI engine...",
        "addCurrentFace": "Add Current Face Data",
        "faceSaved": "Face data saved",
        "noFaceDetected": "No face detected",
        "uploadFaceImage": "Upload a Face Image",
        "personName": "Person Name",
        "noCodeDetected": "No QR code or barcode detected",
        "unitTitle": "Component Title",
        "backgroundColor": "Background Color",
        "titleColor": "Title Color",
        "dataView": "Data",
        "componentView": "Components",
        "platformType": "Platform Type",
        "mixioVersion": "MixIO Version",
        "mixlyServerVersion": "Mixly Programming Server Version",
        "serverClock": "Server Time",
        "updateMixioServer": "Update MixIO Server",
        "updateMixlyServer": "Update Mixly Programming Server",
        "configItem": "Setting",
        "description": "Description",
        "dataType": "Data Type",
        "configHttpPort": "HTTP Port",
        "configHttpsPort": "HTTPS Port",
        "configPrivateKey": "Private Key Path or URL",
        "configCertificate": "Certificate Path or URL",
        "configMqttPort": "MQTT Port",
        "configMqttWsPort": "MQTT WebSocket Port",
        "configMqttWssPort": "MQTT Secure WebSocket Port",
        "configYjsWsPort": "Collaboration WebSocket Port",
        "configYjsWssPort": "Collaboration Secure WebSocket Port",
        "configMaxProjects": "Maximum Projects per User",
        "configMaxOfflineMessages": "Maximum Stored Offline Messages per User",
        "configMaxMessagesPerSecond": "Maximum Messages per Second per User",
        "configAllowRegister": "Allow Self-registration",
        "configAllowOfflineStorage": "Store Messages While Offline",
        "configOfflineMode": "Disable Weather and Map Data",
        "configBaiduClientAk": "Baidu Maps Client AK",
        "configBaiduServerAk": "Baidu Maps Server AK",
        "configTencentKey": "Tencent Maps Key",
        "configAnalyticsLink": "Baidu Analytics Link",
        "configAdminUser": "Admin Console Username",
        "configAdminPassword": "Admin Console Password",
        "configStorageEngine": "Database Engine",
        "configMysqlHost": "MySQL Host",
        "configMysqlPort": "MySQL Port",
        "configMysqlUser": "MySQL Username",
        "configMysqlPassword": "MySQL Password",
        "configMysqlDatabase": "MySQL Database Name",
        "configFooter": "Registration Information Shown on the Home Page",
        "yes": "Yes",
        "no": "No",
        "saveSettingsRestart": "Save Settings and Restart",
        "batchAccountFormat": "Format (one account per line): account,password,security question,answer",
        "addAccounts": "Add Accounts",
        "user": "User",
        "clearMessages": "Clear Messages",
        "resetPassword": "Reset Password",
        "deleteUser": "Delete User",
        "projectCount": "Projects",
        "messageCount": "Messages",
        "actions": "Actions",
        "actionSuccess": "Operation completed successfully",
        "actionFailed": "Operation failed",
        "resetUserPasswordConfirm": "Reset the password for “{{user}}” to “123456”?",
        "deleteUserConfirm": "Delete the user “{{user}}”? This action cannot be undone.",
        "resettingPassword": "Resetting password...",
        "settingsSavedRestarting": "Settings saved. Restarting the server...",
        "abnormalStatus": "Unexpected status",
        "updateCompletedRestart": "Update complete. Restart the MixIO service manually.",
        "updateCompleted": "Update complete",
        "sendingUpdateRequest": "Sending update request...",
        "localVersion": "Local version: {{version}}",
        "cloudVersion": "Cloud version: {{version}}",
        "updateRequired": "Update required: {{value}}",
        "downloadStarted": "Download started...",
        "downloadingProgress": "Downloading: {{progress}}%",
        "extracting": "Extracting...",
        "extractionCompleteWait": "{{version}} extracted. Clearing the cache; this takes about 30 seconds...",
        "downloadFailedExit": "Download failed. Exiting in 5 seconds...",
        "upToDateExit": "Already up to date. Exiting in 5 seconds...",
        "invalidFormat": "Invalid format",
        "userAlreadyExists": "User already exists",
        "connectionFailed": "Connection failed",
        "batchResult": "Succeeded: {{success}}; failed: {{failed}}; reasons: {{reasons}}",
        "newFile": "New File",
        "document": "Document",
        "spreadsheet": "Spreadsheet",
        "image": "Image",
        "file": "File",
        "importFile": "Import File",
        "listViewHint": "List view · Click a row to edit",
        "fileName": "File Name",
        "enterFileName": "Enter a file name",
        "create": "Create",
        "confirmDelete": "Confirm Deletion",
        "deleteFileQuestion": "Delete “{{name}}”?",
        "irreversible": "This action cannot be undone",
        "processing": "Processing...",
        "unknown": "Unknown",
        "downloadSuccess": "Downloaded: {{name}}",
        "fileDownloadFailed": "File download failed",
        "loadFileListFailed": "Failed to load the file list",
        "loadFileListNetworkFailed": "Failed to load the file list. Check your network connection.",
        "noFiles": "No files yet",
        "noFilesHint": "Select “New File” or “Import File” to start using CoDrive",
        "type": "Type",
        "modifiedAt": "Last Modified",
        "size": "Size",
        "edit": "Edit",
        "favoriteSharedFiles": "Saved Shared Files",
        "favoriteSharedFilesHint": "(shared by other users)",
        "from": "From",
        "favoritedAt": "Saved At",
        "status": "Status",
        "shared": "Shared",
        "available": "Available",
        "unavailable": "Unavailable",
        "unfavorite": "Remove",
        "sourceFileUnavailable": "The original file is no longer available",
        "imageOnlineEditUnsupported": "Images cannot be edited online",
        "confirmUnfavorite": "Remove “{{name}}” from your saved files?",
        "shareLink": "Share Link",
        "shareLinkHelp": "Share this link to collaborate on “{{name}}”.",
        "copy": "Copy",
        "copied": "Copied",
        "copiedToClipboard": "Link copied to the clipboard",
        "anyoneCanEdit": "Anyone with this link can view and edit the document",
        "close": "Close",
        "unfavoriteSuccess": "Removed from saved files",
        "unfavoriteFailed": "Failed to remove the saved file",
        "fileDeleteSuccess": "File deleted",
        "fileDeleteFailed": "Failed to delete the file. Try again later.",
        "newDocument": "New Document",
        "newSpreadsheet": "New Spreadsheet",
        "markdownExtensionHint": "The .md extension will be added automatically",
        "csvExtensionHint": "The .csv extension will be added automatically",
        "fileCreated": "Created {{type}}: {{name}}",
        "createFileFailed": "Failed to create the file",
        "createFileRetry": "Failed to create the file. Try again later.",
        "convertedAndUploaded": "Converted and uploaded: {{name}}",
        "uploadFailed": "Upload failed",
        "fileUploadFailed": "File upload failed",
        "excelConversionFailed": "Could not convert the Excel file. Check its format.",
        "docxConversionFailed": "Could not convert the DOCX file. Check its format.",
        "docxReadFailed": "Could not read the DOCX file. Check its format.",
        "uploadSuccess": "Uploaded: {{name}} ({{type}})",
        "tinydbManagement": "TinyDB Data Management",
        "dataList": "Data",
        "refresh": "Refresh",
        "add": "Add",
        "search": "Search",
        "tag": "Tag",
        "showingFrom": "Showing",
        "to": "to",
        "totalRecords": "of",
        "records": "records",
        "searchData": "Search Data",
        "tagKeyword": "Tag Keyword",
        "enterTagKeyword": "Enter a tag keyword",
        "returnType": "Return Type",
        "tagAndValue": "Tags and Values",
        "tagsOnly": "Tags Only",
        "valuesOnly": "Values Only",
        "resultLimit": "Result Limit",
        "inputTag": "Enter a tag",
        "inputValue": "Enter a value",
        "save": "Save",
        "unsavedNewData": "Save or cancel the new entry first",
        "tagRequired": "Tag cannot be empty",
        "valueRequired": "Value cannot be empty",
        "dataAddSuccess": "Data added",
        "addFailed": "Failed to add data: {{message}}",
        "networkError": "Network error. Try again later.",
        "userInfoMissing": "User information not found. Sign in again.",
        "loadDataFailed": "Failed to load data: {{message}}",
        "dataUpdateSuccess": "Data updated",
        "updateFailed": "Update failed: {{message}}",
        "deleteTagConfirm": "Delete the data with tag “{{tag}}”?",
        "previousPage": "Previous",
        "nextPage": "Next",
        "dataDeleteSuccess": "Data deleted",
        "deleteFailedWithMessage": "Delete failed: {{message}}",
        "searchComplete": "Search complete",
        "searchFailed": "Search failed: {{message}}",
        "back": "Back",
        "sharedBy": "Shared by {{user}}",
        "saveToMyDrive": "Save to My Drive",
        "versions": "Versions",
        "saved": "Saved",
        "disconnectedStatus": "Disconnected",
        "addRow": "Add Row",
        "addColumn": "Add Column",
        "deleteRow": "Delete Row",
        "deleteColumn": "Delete Column",
        "onlineCollaboration": "Live Collaboration",
        "fileVersionHistory": "File Version History",
        "loadVersionsFailed": "Failed to load version history",
        "noVersionHistory": "No version history yet",
        "versionHistoryHint": "Versions are recorded automatically when you save the document",
        "createdBy": "Created by {{user}}",
        "view": "View",
        "restore": "Restore",
        "currentVersion": "Current Version",
        "versionPreview": "Version Preview",
        "restoreThisVersion": "Restore This Version",
        "getVersionFailed": "Failed to load the version content",
        "confirmRestoreVersion": "Restore this version? The current content will be overwritten.",
        "versionRestoreSuccess": "Version restored",
        "contentUpdated": "Content updated",
        "restoreVersionFailed": "Failed to restore the version",
        "confirmDeleteVersion": "Delete this version? This action cannot be undone.",
        "versionDeleteSuccess": "Version deleted",
        "deleteVersionFailed": "Failed to delete the version",
        "saving": "Saving...",
        "saveFailed": "Save failed",
        "fileNameRequired": "File name cannot be empty",
        "renameSuccess": "File renamed",
        "renameFailed": "Rename failed",
        "documentEditorTitle": "{{name}} - Document Editor",
        "spreadsheetEditorTitle": "{{name}} - Spreadsheet Editor",
        "collaborationConnected": "Live collaboration connected",
        "collaborationDisconnected": "Collaboration disconnected. Switching to local mode.",
        "collaboratorJoined": "A collaborator joined",
        "collaborationUnavailable": "Live collaboration is unavailable. Using standard mode.",
        "uploadingImage": "Uploading image...",
        "imageUploadSuccess": "Image uploaded",
        "imageUploadFailed": "Image upload failed",
        "uploadImage": "Upload Image",
        "textColor": "Text Color",
        "keepOneRow": "At least one row is required",
        "keepOneColumn": "At least one column is required",
        "csvFormatSuccess": "CSV formatting complete",
        "csvFormatFailed": "CSV formatting failed",
        "fileLoaded": "{{type}} loaded",
        "loadFailed": "Load failed",
        "loadDocumentFailed": "Failed to load the document",
        "unsavedLeaveConfirm": "This document has unsaved changes. Leave anyway?",
        "missingParameters": "Required parameters are missing",
        "unsupportedEditType": "Only documents and spreadsheets can be edited",
        "favoritedToDrive": "Saved to My Drive",
        "favorited": "Saved",
        "favoriteFailed": "Failed to save the shared file",
        "you": "You",
        "editingOnline": "Editing online",
        "unsaved": "Unsaved",
        "chooseTextColor": "Choose Text Color",
        "customColor": "Custom color:",
        "editorPlaceholder": "Write your document here...",
        "connectedStatus": "Connected",
        "connectingStatus": "Connecting...",
        "syncedStatus": "Synced",
        "unknownStatus": "Unknown status",
        "justNow": "Just now",
        "minutesAgo": "{{count}} minutes ago",
        "hoursAgo": "{{count}} hours ago",
        "daysAgo": "{{count}} days ago"
    }
};

Object.keys(JSLangExtensions).forEach(function (languageCode) {
    Object.assign(JSLang[languageCode], JSLangExtensions[languageCode]);
});

function standardizeTraditionalChineseDictionary(dictionary) {
    var terminology = [
        ["項目", "專案"], ["數據", "資料"], ["消息", "訊息"], ["用戶", "使用者"],
        ["服務器", "伺服器"], ["鏈接", "連結"], ["加載", "載入"], ["組件", "元件"],
        ["代碼", "程式碼"], ["視圖", "檢視"], ["運行", "執行"], ["設置", "設定"],
        ["保存", "儲存"], ["文本", "文字"], ["視頻", "影片"], ["攝像頭", "攝影機"],
        ["登錄", "登入"], ["訪問", "存取"], ["復製", "複製"], ["控製", "控制"],
        ["標簽", "標籤"], ["觸髮", "觸發"], ["限製", "限制"], ["字符", "字元"],
        ["布局", "版面配置"], ["編程", "程式設計"], ["當前", "目前"], ["信息", "資訊"],
        ["清空", "清除"], ["添加", "新增"], ["創建", "建立"], ["導入", "匯入"],
        ["發送", "傳送"], ["采集", "蒐集"], ["實時", "即時"], ["郵箱", "電子郵件"]
    ];
    Object.keys(dictionary).forEach(function (key) {
        if (typeof dictionary[key] !== "string") return;
        terminology.forEach(function (pair) {
            dictionary[key] = dictionary[key].split(pair[0]).join(pair[1]);
        });
    });
}

standardizeTraditionalChineseDictionary(JSLang.tw);

var arrLang = {
    "en": {
        "OPENSRC": "Open Repo",
        "ADMINDASH": "Admin Dashboard",
        "TOPIC": "Topic",
        "MESSAGE": "Message",
        "TIME": "Time",
        "DATAMANAGE": "Data",
        "CODRIVE": "Drive",
        "ADMIN": "Admin",
        "BASICADMIN": "Basic",
        "USERADMIN": "Users",
        "DATAADMIN": "Data",
        "UPEMAIL": "E-mail: ",
        "EMAIL": "placeholder$E-mail Address",
        "PASSWORD": "placeholder$Password",
        "LOGIN": "Sign in",
        "MIXLYKEY": "placeholder$Mixly Key",
        "LOGIN2": "Sign in",
        "VFCODE": "placeholder$Project Verification Code",
        "BROWSE": "Browse",
        "RESET": "Reset Password",
        "SIGNUP": "Sign Up",
        "GUIDE": "Quick Guide",
        "ANDROID": "App",
        "MANAGE": "Manage",
        "PROJECTSMANAGE": "Projects",
        "STORAGEMANAGE": "Storage",
        "SHAREMANAGE": "Share",
        "SETTINGS": "Settings",
        "LOGOUT": "Log out",
        "IMPORT": "Import user projects",
        "EXPORT": "Export user projects",
        "CONNECTINGSERVER": "Connecting server...",
        "MANAGECOUNT": "Projects Managed",
        "OFFLINECOUNT": "Temporary Messages Reserved",
        "MOREINFO": "Go to 'Storage' for more info ",
        "PREV": "Prev",
        "NEXT": "Next",
        "DATA": "Data",
        "PROJ": "Units",
        "LOGIC": "Logic",
        "REGACC": "Sign Up",
        "RPTPASS": "placeholder$Repeat Password",
        "RSTPASS": "Reset password",
        "HAVEACC": "Have an account? Click to sign in",
        "SRCPRJNAME": "Source Project",
        "SHARETIME": "Share Time",
        "AUCODE": "Authorization Code",
        "STATUSNOW": "Status",
        "USEDTIME": "Used Times",
        "OPTIONS": "Options",
        "ONSHARE": "Sharing",
        "OFFSHARE": "Paused",
        "VERIFYQ": "Reset Password",
        "VERIFYDES": "We need to verify your security question to confirm your identity.",
        "ANSWERQ": "Answer Question",
        "REGEMAIL": "placeholder$Email address used when registering",
        "ANSWERVQ": "Please answer the preset security question and set a new password.",
        "ANSWERINPUT": "placeholder$Answer",
        "NEWPASS": "placeholder$New Password",
        "NEWPASSRPT": "placeholder$Repeat New Password",
        "PRJNAME": "Project Name",
        "SETQ": "Set Security Verification Question",
        "SETQDES": "Please set the security verification question and its answer as the credential to retrieve the password when necessary.",
        "CHANGEQ": "Change Question",
        "SETANS": "placeholder$Answer",
        "CFMSET": "Confirm"
    },
    "zh": {
        "OPENSRC": "开源仓库",
        "ADMINDASH": "管理后台",
        "TOPIC": "主题",
        "MESSAGE": "消息",
        "TIME": "时间",
        "DATAMANAGE": "数据管理",
        "CODRIVE": "协作云盘",
        "ADMIN": "管理",
        "BASICADMIN": "基础设置",
        "USERADMIN": "批量注册",
        "DATAADMIN": "用户管理",
        "UPEMAIL": "注册邮箱：",
        "EMAIL": "placeholder$请输入电子邮箱地址",
        "PASSWORD": "placeholder$请输入密码",
        "LOGIN": "登录MixIO",
        "MIXLYKEY": "placeholder$请输入Mixly Key",
        "LOGIN2": "登录MixIO",
        "VFCODE": "placeholder$请输入项目授权码",
        "BROWSE": "访问MixIO项目",
        "RESET": "重置密码",
        "SIGNUP": "注册账号",
        "GUIDE": "入门指南",
        "ANDROID": "安卓微端",
        "MANAGE": "管理",
        "PROJECTSMANAGE": "项目管理",
        "STORAGEMANAGE": "数据管理",
        "SHAREMANAGE": "共享管理",
        "SETTINGS": "设置",
        "LOGOUT": "退出登录",
        "IMPORT": "导入项目",
        "EXPORT": "导出项目",
        "CONNECTINGSERVER": "正在连接服务器",
        "MANAGECOUNT": "管理项目数",
        "OFFLINECOUNT": "离线消息数",
        "MOREINFO": "前往“存储管理”中查看更多信息 ",
        "PREV": "上页",
        "NEXT": "下页",
        "DATA": "数据",
        "PROJ": "组件",
        "LOGIC": "逻辑",
        "REGACC": "注册账号",
        "RPTPASS": "placeholder$重复密码",
        "RSTPASS": "重置密码",
        "HAVEACC": "已有帐号？点击此处登录",
        "SRCPRJNAME": "原项目名称",
        "SHARETIME": "共享时间",
        "AUCODE": "授权码",
        "STATUSNOW": "当前状态",
        "USEDTIME": "被使用次数",
        "OPTIONS": "操作",
        "ONSHARE": "正在共享",
        "OFFSHARE": "暂停共享",
        "VERIFYQ": "验证密保问题",
        "VERIFYDES": "我们需要验证您的密保问题以确认身份。",
        "ANSWERQ": "回答密保问题",
        "REGEMAIL": "placeholder$注册时使用的电子邮件地址",
        "ANSWERVQ": "请回答预设的密保问题，并设定新密码。",
        "ANSWERINPUT": "placeholder$请输入问题答案",
        "NEWPASS": "placeholder$请输入新密码",
        "NEWPASSRPT": "placeholder$重复输入新密码",
        "PRJNAME": "项目名称",
        "SETQ": "设置密保验证问题",
        "SETQDES": "请您设置密码保护问题及其答案，以作为必要时用以找回密码的凭据。",
        "CHANGEQ": "换问题",
        "SETANS": "placeholder$设置问题答案",
        "CFMSET": "确定设置"
    },
    "tw": {
        "OPENSRC": "開源倉庫",
        "ADMINDASH": "管理後台",
        "TOPIC": "主題",
        "MESSAGE": "消息",
        "TIME": "時間",
        "DATAMANAGE": "數據管理",
        "CODRIVE": "協作雲盤",
        "ADMIN": "管理",
        "BASICADMIN": "基礎設置",
        "USERADMIN": "批量註冊",
        "DATAADMIN": "數據管理",
        "UPEMAIL": "註冊郵箱：",
        "EMAIL": "placeholder$請輸入電子郵箱地址",
        "PASSWORD": "placeholder$請輸入密碼",
        "LOGIN": "登錄MixIO",
        "MIXLYKEY": "placeholder$請輸入Mixly Key",
        "LOGIN2": "登錄MixIO",
        "VFCODE": "placeholder$請輸入項目授權碼",
        "BROWSE": "訪問MixIO項目",
        "RESET": "重置密碼",
        "SIGNUP": "註冊賬號",
        "GUIDE": "入門指南",
        "ANDROID": "安卓微端",
        "MANAGE": "管理",
        "PROJECTSMANAGE": "項目管理",
        "STORAGEMANAGE": "存儲管理",
        "SHAREMANAGE": "共享管理",
        "SETTINGS": "設置",
        "LOGOUT": "退出登錄",
        "IMPORT": "匯入用戶項目",
        "EXPORT": "匯出用戶項目",
        "CONNECTINGSERVER": "正在連接服務器",
        "MANAGECOUNT": "管理項目數",
        "OFFLINECOUNT": "離線消息數",
        "MOREINFO": "前往「存儲管理」中查看更多信息 ",
        "PREV": "上頁",
        "NEXT": "下頁",
        "DATA": "數據",
        "PROJ": "組件",
        "LOGIC": "邏輯",
        "REGACC": "註冊賬號",
        "RPTPASS": "placeholder$重復密碼",
        "RSTPASS": "重置密碼",
        "HAVEACC": "已有帳號？點擊此處登錄",
        "SRCPRJNAME": "原項目名稱",
        "SHARETIME": "共享時間",
        "AUCODE": "授權碼",
        "STATUSNOW": "當前狀態",
        "USEDTIME": "被使用次數",
        "OPTIONS": "操作",
        "ONSHARE": "正在共享",
        "OFFSHARE": "暫停共享",
        "VERIFYQ": "驗證密保問題",
        "VERIFYDES": "我們需要驗證您的密保問題以確認身份。",
        "ANSWERQ": "回答密保問題",
        "REGEMAIL": "placeholder$註冊時使用的電子郵件地址",
        "ANSWERVQ": "請回答預設的密保問題，並設定新密碼。",
        "ANSWERINPUT": "placeholder$請輸入問題答案",
        "NEWPASS": "placeholder$請輸入新密碼",
        "NEWPASSRPT": "placeholder$重復輸入新密碼",
        "PRJNAME": "項目名稱",
        "SETQ": "設置密保驗證問題",
        "SETQDES": "請您設置密碼保護問題及其答案，以作為必要時用以找回密碼的憑據。",
        "CHANGEQ": "換問題",
        "SETANS": "placeholder$設置問題答案",
        "CFMSET": "確定設置"
    }
};
Object.assign(arrLang.tw, {
    "OPENSRC": "開源程式庫",
    "ADMINDASH": "管理後台",
    "DATAMANAGE": "資料管理",
    "CODRIVE": "協作雲端硬碟",
    "BASICADMIN": "基本設定",
    "USERADMIN": "批次註冊",
    "DATAADMIN": "使用者管理",
    "UPEMAIL": "註冊電子郵件：",
    "EMAIL": "placeholder$請輸入電子郵件地址",
    "LOGIN": "登入 MixIO",
    "VFCODE": "placeholder$請輸入專案授權碼",
    "BROWSE": "開啟 MixIO 專案",
    "RESET": "重設密碼",
    "SIGNUP": "註冊帳號",
    "PROJECTSMANAGE": "專案管理",
    "STORAGEMANAGE": "儲存空間管理",
    "SHAREMANAGE": "共享管理",
    "SETTINGS": "設定",
    "LOGOUT": "登出",
    "IMPORT": "匯入使用者專案",
    "EXPORT": "匯出使用者專案",
    "CONNECTINGSERVER": "正在連線至伺服器",
    "MANAGECOUNT": "管理的專案數量",
    "OFFLINECOUNT": "離線訊息數量",
    "MOREINFO": "前往「儲存空間管理」查看更多資訊",
    "PREV": "上一頁",
    "PROJ": "元件",
    "REGACC": "註冊帳號",
    "RPTPASS": "placeholder$再次輸入密碼",
    "RSTPASS": "重設密碼",
    "HAVEACC": "已有帳號？按此登入",
    "SRCPRJNAME": "原始專案名稱",
    "SHARETIME": "共享時間",
    "STATUSNOW": "目前狀態",
    "USEDTIME": "使用次數",
    "ONSHARE": "共享中",
    "OFFSHARE": "暫停共享",
    "VERIFYQ": "驗證安全問題",
    "VERIFYDES": "請回答安全問題以確認您的身分。",
    "ANSWERQ": "回答安全問題",
    "REGEMAIL": "placeholder$註冊時使用的電子郵件地址",
    "ANSWERVQ": "請回答預設的安全問題，並設定新密碼。",
    "ANSWERINPUT": "placeholder$請輸入問題答案",
    "NEWPASSRPT": "placeholder$再次輸入新密碼",
    "PRJNAME": "專案名稱",
    "SETQ": "設定安全問題",
    "SETQDES": "請設定安全問題及答案，以便日後找回密碼。",
    "CHANGEQ": "更換問題",
    "SETANS": "placeholder$設定問題答案",
    "CFMSET": "確認設定"
});

Object.assign(arrLang.en, {
    "OPENSRC": "Open-source Repository",
    "ADMINDASH": "Admin Console",
    "DATAMANAGE": "Data Management",
    "CODRIVE": "CoDrive",
    "BASICADMIN": "General Settings",
    "USERADMIN": "Batch Registration",
    "DATAADMIN": "User Management",
    "UPEMAIL": "Registration Email:",
    "LOGIN": "Sign in to MixIO",
    "VFCODE": "placeholder$Project authorization code",
    "BROWSE": "Open a MixIO Project",
    "RESET": "Reset Password",
    "SIGNUP": "Create Account",
    "STORAGEMANAGE": "Storage Management",
    "SHAREMANAGE": "Sharing Management",
    "SETTINGS": "Settings",
    "LOGOUT": "Sign Out",
    "IMPORT": "Import User Projects",
    "EXPORT": "Export User Projects",
    "CONNECTINGSERVER": "Connecting to the server",
    "MANAGECOUNT": "Managed Projects",
    "OFFLINECOUNT": "Offline Messages",
    "MOREINFO": "Go to Storage Management for more information",
    "REGACC": "Create Account",
    "RPTPASS": "placeholder$Confirm password",
    "RSTPASS": "Reset Password",
    "HAVEACC": "Already have an account? Sign in",
    "SRCPRJNAME": "Original Project Name",
    "SHARETIME": "Shared At",
    "STATUSNOW": "Current Status",
    "USEDTIME": "Times Used",
    "ONSHARE": "Sharing",
    "OFFSHARE": "Sharing Paused",
    "VERIFYQ": "Verify Security Question",
    "VERIFYDES": "Answer your security question to confirm your identity.",
    "ANSWERQ": "Answer Security Question",
    "REGEMAIL": "placeholder$Email address used during registration",
    "ANSWERVQ": "Answer your security question and set a new password.",
    "ANSWERINPUT": "placeholder$Enter your answer",
    "NEWPASS": "placeholder$Enter a new password",
    "NEWPASSRPT": "placeholder$Confirm the new password",
    "SETQ": "Set a Security Question",
    "SETQDES": "Set a security question and answer to help recover your password.",
    "SETANS": "placeholder$Enter an answer",
    "CFMSET": "Save Security Question"
});
standardizeTraditionalChineseDictionary(arrLang.tw);
var lang = "en";

function normalizeLanguage(languageCode) {
    var code = String(languageCode || "").replace("_", "-").toLowerCase();
    if (code === "tw" || code === "zh-tw" || code === "zh-hk" || code === "zh-mo" || code.indexOf("zh-hant") === 0) return "tw";
    if (code === "zh" || code.indexOf("zh-") === 0) return "zh";
    return code === "en" || code.indexOf("en-") === 0 ? "en" : "en";
}

function getTranslationEntry(key, languageCode) {
    var code = normalizeLanguage(languageCode || lang);
    if (JSLang[code] && Object.prototype.hasOwnProperty.call(JSLang[code], key)) return JSLang[code][key];
    if (arrLang[code] && Object.prototype.hasOwnProperty.call(arrLang[code], key)) return arrLang[code][key];
    if (JSLang.en && Object.prototype.hasOwnProperty.call(JSLang.en, key)) return JSLang.en[key];
    if (arrLang.en && Object.prototype.hasOwnProperty.call(arrLang.en, key)) return arrLang.en[key];
    return key;
}

function i18n(key, params, languageCode) {
    var value = String(getTranslationEntry(key, languageCode));
    var attributeSeparator = value.indexOf("$");
    if (attributeSeparator > 0) value = value.slice(attributeSeparator + 1);
    Object.keys(params || {}).forEach(function (paramKey) {
        value = value.split("{{" + paramKey + "}}").join(String(params[paramKey]));
    });
    return value;
}

var dataTableLanguages = {
    "zh": {
        "sProcessing": "处理中...", "sLengthMenu": "每页 _MENU_ 项", "sZeroRecords": "没有匹配结果",
        "sInfo": "显示第 _START_ 至 _END_ 项，共 _TOTAL_ 项", "sInfoEmpty": "暂无记录",
        "sInfoFiltered": "（从 _MAX_ 项结果中筛选）", "sSearch": "搜索：", "sEmptyTable": "表中暂无数据",
        "sLoadingRecords": "加载中...", "oPaginate": { "sFirst": "首页", "sPrevious": "上一页", "sNext": "下一页", "sLast": "末页" },
        "oAria": { "sSortAscending": "：按升序排列此列", "sSortDescending": "：按降序排列此列" }
    },
    "tw": {
        "sProcessing": "處理中...", "sLengthMenu": "每頁 _MENU_ 項", "sZeroRecords": "沒有相符結果",
        "sInfo": "顯示第 _START_ 至 _END_ 項，共 _TOTAL_ 項", "sInfoEmpty": "目前沒有記錄",
        "sInfoFiltered": "（從 _MAX_ 項結果中篩選）", "sSearch": "搜尋：", "sEmptyTable": "表格中目前沒有資料",
        "sLoadingRecords": "載入中...", "oPaginate": { "sFirst": "第一頁", "sPrevious": "上一頁", "sNext": "下一頁", "sLast": "最後一頁" },
        "oAria": { "sSortAscending": "：依升冪排列此欄", "sSortDescending": "：依降冪排列此欄" }
    },
    "en": {
        "sProcessing": "Processing...", "sLengthMenu": "Show _MENU_ entries per page", "sZeroRecords": "No matching records",
        "sInfo": "Showing _START_ to _END_ of _TOTAL_ entries", "sInfoEmpty": "No entries to show",
        "sInfoFiltered": "(filtered from _MAX_ total entries)", "sSearch": "Search:", "sEmptyTable": "No data available",
        "sLoadingRecords": "Loading...", "oPaginate": { "sFirst": "First", "sPrevious": "Previous", "sNext": "Next", "sLast": "Last" },
        "oAria": { "sSortAscending": ": sort this column in ascending order", "sSortDescending": ": sort this column in descending order" }
    }
};

function getDataTableLanguage(languageCode) {
    return dataTableLanguages[normalizeLanguage(languageCode || lang)];
}

function translateElement(element) {
    var key = element.getAttribute("key") || element.getAttribute("data-i18n");
    if (!key) return;
    var value = String(getTranslationEntry(key));
    var parts = value.split("$");
    if (parts.length > 1) {
        element.setAttribute(parts[0], parts.slice(1).join("$"));
    } else if ((element.tagName === "INPUT" || element.tagName === "TEXTAREA") && element.hasAttribute("placeholder")) {
        element.setAttribute("placeholder", value);
    } else {
        element.textContent = value;
    }
}

function applyTranslations(root) {
    if (typeof document === "undefined") return;
    var scope = root && root.querySelectorAll ? root : document;
    if (scope.matches && scope.matches(".lang,[data-i18n]")) translateElement(scope);
    Array.prototype.forEach.call(scope.querySelectorAll(".lang,[data-i18n]"), translateElement);
    document.documentElement.setAttribute("lang", lang === "tw" ? "zh-Hant" : (lang === "zh" ? "zh-Hans" : "en"));
}

function setCorrectButtonStatus() {
    if (typeof $ === "undefined") return;
    $(".translate").removeClass("btn-primary").addClass("btn-secondary");
    $("#" + lang).removeClass("btn-secondary").addClass("btn-primary");
}

function setLanguage(languageCode, persist) {
    lang = normalizeLanguage(languageCode);
    if (persist !== false && typeof localStorage !== "undefined") {
        try { localStorage.setItem("lang", lang); } catch (e) { /* Storage may be disabled. */ }
    }
    applyTranslations();
    setCorrectButtonStatus();
    if (typeof window !== "undefined" && typeof window.CustomEvent === "function") {
        window.dispatchEvent(new CustomEvent("mixio:languagechange", { detail: { lang: lang } }));
    }
    return lang;
}

if (typeof window !== "undefined") {
    var storedLanguage = null;
    try { storedLanguage = window.localStorage && window.localStorage.getItem("lang"); } catch (e) { /* Storage may be disabled. */ }
    lang = normalizeLanguage(storedLanguage || (typeof navigator !== "undefined" ? navigator.language : "en"));
    window.i18n = i18n;
    window.applyTranslations = applyTranslations;
    window.setLanguage = setLanguage;
    window.getDataTableLanguage = getDataTableLanguage;
    window.getCurrentLanguage = function () { return lang; };
}

if (typeof module !== "undefined" && module.exports) {
    module.exports = { JSLang: JSLang, arrLang: arrLang, JSLangExtensions: JSLangExtensions, lang: lang, normalizeLanguage: normalizeLanguage, i18n: i18n, getDataTableLanguage: getDataTableLanguage };
}

if (typeof $ !== "undefined" && typeof document !== "undefined") {
    $(function () {
        applyTranslations();
        setCorrectButtonStatus();
        $(document).on("click", ".translate", function () {
            setLanguage($(this).attr("id"));
        });
    });
}
