version: '1.0'
name: mixio_build
displayName: 自动编译
triggers:
  trigger: manual
  push:
    branches:
      prefix:
        - ''
stages:
  - name: stage-4cddc51c
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 12.16.1
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - npm install pkg -g
          - npm install
          - cd src
          - npm install
          - cd ../
          - version="{
          - '    \"version\":\"1.9.0\",'
          - '    \"platform\":\"win-x64\",'
          - '    \"node-version\":\"12\"'
          - '}"'
          - rm -rf mixio_win_x64
          - mkdir mixio_win_x64
          - cd mixio_win_x64
          - echo "${version}" > version.json
          - mkdir src
          - mkdir logs
          - cd ../
          - cd src
          - pkg -t node12-win-x64 package.json
          - mv -f loader ../mixio_win_x64/src/loader
          - cp -r certs ../mixio_win_x64/src
          - cp config.json ../mixio_win_x64/src/config.json
          - cp mixio.empty.db ../mixio_win_x64/src/mixio.db
          - cp -r reserve ../mixio_win_x64/src
          - cd ../
          - pkg -t node12-win-x64 package.json
          - mv -f mixio mixio_win_x64/mixio
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - mixio_win_x64
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
